language: node_js
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
  - "8"
  - "10"
matrix:
  include:
  - node_js: "6"
    env: WAIT=1
before_install:
  - npm i -g yarn --cache-min 999999999
install:
  - yarn
notifications:
    email: false
before_script:
  - yarn add codecov --dev
script:
  - if [ ! "$WAIT" ]; then yarn test; else travis_wait yarn test; fi
after_script:
  - codecov
git:
  depth: 5
