backend:
  name: test-repo

display_url: https://example.com

publish_mode: editorial_workflow
media_folder: assets/uploads
media_library:
  name: uploadcare
  config:
    publicKey: demopublickey

collections: # A list of collections the CMS should be able to edit
  - name: "page"
    label: "Page"
    folder: "site/content"
    slug: "{{slug}}"
    create: true
    fields:
      - { label: "Titel", name: "title", widget: "string", tagname: "h1" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Media (works)", name: "image_single", widget: "image" }
