menu:
  docs:
    - name: intro
      title: Intro to Netlify CMS
    - name: account
      title: Account Settings
    - name: config
      title: Configuring your Site
    - name: media
      title: Media
    - name: workflow
      title: Workflow
    - name: fields
      title: Fields
    - name: guides
      title: Guides
    - name: customization
      title: Customization
    - name: contributing
      title: Contributing
