name: dast
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checout
      uses: actions/checkout@v4
    - name: OWASP ZAP Scan
      uses: zaproxy/action-full-scan@v0.1.0
      
