name: 'Docs Linting:'
on:
  push:
    branches:
      - master

    paths:
      - '.github/workflows/docslint.yml'
      - 'website/**'

  pull_request:
    types: [opened, synchronize, reopened]

    paths:
      - '.github/workflows/docslint.yml'
      - 'website/**'

jobs:
  Prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Vale Linter
        uses: errata-ai/vale-action@134d1c45dc68d3ac9b1cfde0fa9389557aa5486f
        with:
          # Optional
          files: website/content/docs
        env:
          # Required
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
