name: Secure Pipeline
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build Docker image
        run: docker build -t decapmcmc:latest .
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
           docker tag decapmcmc:latest your-registry/decapmcmc:${{ github.sha }}
           docker push your-registry/decapmcmc:${{ github.sha }}

